In [2]:
import pandas as pd

df = pd.read_csv('macro_barcarena_tratado.csv')
df

,ano,PIB,Impostos,vab_bruto,vab_agropecuaria,vab_industria,vab_servicos,vab_governo
0,2010,2227149.609,540699.053,1686450.556,52462.0,842954.0,565801.667,225232.853
1,2011,2460397.520,567546.817,1892850.703,56937.0,997205.0,567624.066,271084.561
2,2012,2006449.481,593976.556,1412472.925,64451.0,364438.0,677425.521,306159.104
3,2013,2658971.938,590890.879,2068081.059,83328.0,997191.0,654005.308,333555.950
4,2014,3902984.552,797264.308,3105720.244,78492.0,1634683.0,1021477.477,371067.151
5,2015,5513143.805,956512.030,4556631.776,93987.0,2897486.0,1163692.571,401466.206
6,2016,5014168.695,1058713.516,3955455.180,80465.0,2292035.0,1123461.437,459494.145
7,2017,4818669.203,1092526.796,3726142.407,94650.0,2003925.0,1123176.770,504390.371
8,2018,4737435.563,1104325.362,3633110.201,86391.0,1892147.0,1122652.448,531919.773
9,2019,5364844.356,1399694.124,3965150.232,79134.0,2124330.0,1195963.430,565722.806
10,2020,7433645.296,1674585.163,5759060.133,167676.0,3665438.0,1274475.444,651470.235
11,2021,9242378.136,2276306.299,6966071.837,181646.0,4694445.0,1468235.100,621746.319

In [3]:
import plotly.express as px

fig = px.bar(df, x='ano',y='PIB')
fig.show()

In [ ]:
import plotly.graph_objects as go
from utils import formatar_moeda_br

df['Impostos_text'] = df['Impostos'] * 1000
df['Impostos_text'] = df['Impostos_text'].round(2)
df["Impostos_text"] = df["Impostos_text"].apply(
    lambda x: f"R$ {x:,.0f}".replace(",", "X").replace(".", ",").replace("X", ".")
)

df['vab_bruto_text'] = df['vab_bruto'] * 1000
df['vab_bruto_text'] = df['vab_bruto_text'].round(2)
df["vab_bruto_text"] = df["vab_bruto_text"].apply(
    lambda x: f"R$ {x:,.0f}".replace(",", "X").replace(".", ",").replace("X", ".")
)


df['Impostos_p'] = (df['Impostos'] / df['PIB'] * 100).round(2).astype(str) + '%'



fig = go.Figure(data=[
    go.Bar(x=df['ano'],y=df['Impostos'],name='Impostos',text=df['Impostos_text']),
    go.Bar(x=df['ano'], y=df['vab_bruto'],name='Valor adicionado bruto', text=df['vab_bruto_text'],textposition="outside",textfont=dict(color="black",size=25)),
    go.Scatter(x=df['ano'], y=df['Impostos'], mode='markers+text',text=df['Impostos_p'], textposition="top center",name="proporção imposto/pib",textfont=dict(color="white",size=10))
])

fig.update_layout(barmode='stack')
fig.show()

In [31]:
df

,ano,PIB,Impostos,vab_bruto,vab_agropecuaria,vab_industria,vab_servicos,vab_governo,Impostos_text,Impostos_p,vab_bruto_text
0,2010,2227149.609,540699.053,1686450.556,52462.0,842954.0,565801.667,225232.853,R$ 540.699.053,24.28%,R$ 1.686.450.556
1,2011,2460397.520,567546.817,1892850.703,56937.0,997205.0,567624.066,271084.561,R$ 567.546.817,23.07%,R$ 1.892.850.703
2,2012,2006449.481,593976.556,1412472.925,64451.0,364438.0,677425.521,306159.104,R$ 593.976.556,29.6%,R$ 1.412.472.925
3,2013,2658971.938,590890.879,2068081.059,83328.0,997191.0,654005.308,333555.950,R$ 590.890.879,22.22%,R$ 2.068.081.059
4,2014,3902984.552,797264.308,3105720.244,78492.0,1634683.0,1021477.477,371067.151,R$ 797.264.308,20.43%,R$ 3.105.720.244
5,2015,5513143.805,956512.030,4556631.776,93987.0,2897486.0,1163692.571,401466.206,R$ 956.512.030,17.35%,R$ 4.556.631.776
6,2016,5014168.695,1058713.516,3955455.180,80465.0,2292035.0,1123461.437,459494.145,R$ 1.058.713.516,21.11%,R$ 3.955.455.180
7,2017,4818669.203,1092526.796,3726142.407,94650.0,2003925.0,1123176.770,504390.371,R$ 1.092.526.796,22.67%,R$ 3.726.142.407
8,2018,4737435.563,1104325.362,3633110.201,86391.0,1892147.0,1122652.448,531919.773,R$ 1.104.325.362,23.31%,R$ 3.633.110.201
9,2019,5364844.356,1399694.124,3965150.232,79134.0,2124330.0,1195963.430,565722.806,R$ 1.399.694.124,26.09%,R$ 3.965.150.232
10,2020,7433645.296,1674585.163,5759060.133,167676.0,3665438.0,1274475.444,651470.235,R$ 1.674.585.163,22.53%,R$ 5.759.060.133
11,2021,9242378.136,2276306.299,6966071.837,181646.0,4694445.0,1468235.100,621746.319,R$ 2.276.306.299,24.63%,R$ 6.966.071.837

In [30]:
fig = go.Figure(data=[
    go.Bar(x=df['ano'], y=df['vab_agropecuaria'],name='Valor adicionado agropecuária', text=df['vab_agropecuaria'],textposition="inside",textfont=dict(color="black",size=25)),
    go.Bar(x=df['ano'], y=df['vab_governo'],name='Valor adicionado governo', text=df['vab_governo'],textposition="inside",textfont=dict(color="black",size=25)),
    go.Bar(x=df['ano'], y=df['vab_industria'],name='Valor adicionado industria', text=df['vab_industria'],textposition="inside",textfont=dict(color="black",size=8)),
    go.Bar(x=df['ano'], y=df['vab_servicos'],name='Valor adicionado serviços', text=df['vab_servicos'],textposition="inside",textfont=dict(color="black",size=25)),
])



fig.update_layout(barmode='stack')
fig.show()